Homework 13 Develop and testing Ansible roles and playbooks
sheriffed3/infra pull request #10
Opened 2017-09-29 13:10 UTC by sheriffed3

2017-09-29 16:32 UTC, Artemmkin commented on ansible/roles/db/molecule/default/.molecule/.vagrant/machines/instance/virtualbox/action_set_name
> +1506679952
не добавил папку .vagrant в гитигнор и смотри, что прилетело. Нужны ли эти файлы?

2017-09-29 16:32 UTC, Artemmkin commented on ansible/roles/db/molecule/default/.molecule/.vagrant/machines/instance/virtualbox/synced_folders
> +{"virtualbox":{"/vagrant":{"guestpath":"/vagrant","hostpath":"/home/sher/OTUS/infra/branches/ansible-5/ansible/roles/db/molecule/default/.molecule","disabled":false,"__vagrantfile":true}}}
смотри сколько мусора

2017-09-29 16:38 UTC, Artemmkin commented on ansible/roles/db/molecule/default/tests/test_default.py
> +    ("tcp://0.0.0.0:27017")
выглядит очень странно и я не думаю, что этот тест работает. Ты проверял его, он выполняется? 
У объектов класса сокет, если метод [is_listening](http://testinfra.readthedocs.io/en/latest/modules.html#socket) предполагалось, что будете использовать его

2017-09-29 16:42 UTC, Artemmkin commented on packer/db.json
> +      "playbook_file": "../ansible/db.yml"
смотри, как теги можно в провижинер передать [gist](https://gist.github.com/Artemmkin/86f2a73544e84203841dbb7d898b2222)

2017-09-29 16:46 UTC, Artemmkin requested changes
В целом выглядит все хорошо 👍 но меня смущает, что прилетело в репозиторий куча ненужного мусора: логи машины, запущенной вагрантом, сама папка `.vagrant`. Это нужно удалить из директории и добавить эти файлы в гитигнор. Также посмотри, нужна ли нам папка `.molecule` в ней тоже самое хранится похоже.
Проверь также  testinfra тест (см. коммент выше)

2017-09-29 16:46 UTC, Artemmkin commented
как поправишь - отпишись здесь или в чате, я заапрувлю

2017-10-02 09:05 UTC, sheriffed3 commented
Поправил замечания, просьба проверить.

2017-10-02 09:32 UTC, Artemmkin commented
Вижу, что поправил гитигнор, но эти файлы и директории, что добавил, нужно все равно удалить )

2017-10-02 09:35 UTC, Artemmkin commented
то есть их удалить из репозитория и сказать гиту их больше не отслеживать. Как это сделать можно посмотреть [здесь](https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste) в ответах `git rm --cached filename.txt`

2017-10-02 10:31 UTC, sheriffed3 commented
Готово:
1. svn rm -m "Delete .molecule"  https://github.com/sheriffed3/infra/branches/ansible-5/ansible/roles/db/molecule/default/.molecule
Committing transaction...
Committed revision 93.

2. svn rm -m "Delete .vagrant"  https://github.com/sheriffed3/infra/branches/ansible-5/ansible/.vagrant
Committing transaction...
Committed revision 95.

2017-10-02 10:32 UTC, Artemmkin commented
svn? O_o

2017-10-02 10:33 UTC, Artemmkin commented
мы какой систему контроля версий пользуемся?

2017-10-02 10:35 UTC, sheriffed3 commented
На домашнем маке у меня гит, а на рабочей убунте RapidSVN

2017-10-02 10:37 UTC, Artemmkin commented
тебе кажется ок, мешать так системы?

2017-10-02 10:37 UTC, sheriffed3 commented
Точнее клиент SourceTree на маке

2017-10-02 10:39 UTC, sheriffed3 commented
даже не знаю, я до начала обучения вообще не работал с гитхабом. А в чем проблема? Они же вроде как та, так и другая работает с гихабом.

2017-10-02 10:42 UTC, Artemmkin commented
Это две разные системы контроля версий, который отличаются архитектурными подходами к хранению версий и способом хранения информации. Это выглядит просто очень не ок. 
Гит тебе предоставляет команды для всего, даже для работы с svn репами, там тем более есть команда, как перестать отслеживать документ (и я тебе ее уже скинул).

2017-10-02 10:44 UTC, Artemmkin approved these changes

2017-10-02 10:45 UTC, Artemmkin commented
пул реквест одобряю, но советую почитать про различие гита от других систем контроля версий и для чего в гите есть команды для работы с svn

2017-10-02 10:48 UTC, merged